# Generated by Django 3.2.25 on 2024-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('userName', models.TextField(max_length=20)),
            ],
        ),
    ]
