# Generated by Django 3.2.25 on 2024-12-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241209_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
